apiVersion: v1
kind: Service
metadata:
  name: ms-helloworld-svc
  namespace: test
spec:
  externalTrafficPolicy: Cluster
  ports:
    - name: ms-mobil-partner
      port: 3000
      protocol: TCP
      targetPort: 8080
      nodePort: 30080
  selector:
    app: ms-helloworld
    tier: frontend
  type: NodePort
